//! Component authoring contracts used by generated SDK code.

use serde::{Deserialize, Serialize};

/// How a component's stable schema is realized by the selected build plan.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ComponentMode {
    /// A host-compiled Rust type that does not cross a portable boundary.
    HostTyped,
    /// A versioned schema shared by static package build units.
    GeneratedSharedSchema,
    /// A validated ABI-POD schema registered by the dedicated runtime bridge.
    RuntimeDynamic,
}

/// A component declaration generated by [`crate::component`].
///
/// Implementations are sealed. Package code declares the contract through the
/// attribute macro instead of constructing a second registration truth.
pub trait ComponentContract: SealedComponent {
    /// Returns the macro-generated seed consumed by [`crate::registration_ir`].
    #[doc(hidden)]
    fn __registration_seed() -> ComponentSeed;
}

/// Seal implemented only by generated component declarations.
#[doc(hidden)]
pub trait SealedComponent {}

/// Safe compile-time marker for the fixed-width field vocabulary accepted by
/// the first SDK prototype.
///
/// This marker does not perform Bevy dynamic component registration and is not
/// the unsafe `ComponentDescriptor` boundary described by ADR 0023.
#[doc(hidden)]
pub trait AbiPodField {}

macro_rules! abi_pod_scalars {
    ($($scalar:ty),+ $(,)?) => {
        $(impl AbiPodField for $scalar {})+
    };
}

abi_pod_scalars!(u8, i8, u16, i16, u32, i32, u64, i64, f32, f64);

impl<T, const LENGTH: usize> AbiPodField for [T; LENGTH] where T: AbiPodField {}

/// Unvalidated component seed emitted by macro expansion.
#[derive(Clone, Debug)]
#[doc(hidden)]
pub struct ComponentSeed {
    pub(crate) id: &'static str,
    pub(crate) schema: Option<&'static str>,
    pub(crate) mode: ComponentMode,
    pub(crate) rust_api_descriptor: &'static str,
}

impl ComponentSeed {
    /// Creates a component seed for generated code.
    #[must_use]
    #[doc(hidden)]
    pub const fn new(
        id: &'static str,
        schema: Option<&'static str>,
        mode: ComponentMode,
        rust_api_descriptor: &'static str,
    ) -> Self {
        Self {
            id,
            schema,
            mode,
            rust_api_descriptor,
        }
    }
}
