//! Compiler-owned inputs, runtime tables, and activation receipts.

use std::collections::{BTreeMap, BTreeSet};

use latticeaxiom_compose::{
    AffordanceDefinition, AffordancePolicy, CompositionSpec, ContentRoleDefinition,
    LockedGameGraph, ManifestProducer, NumericRegistrationId, RegistrationImage, RegistrationKind,
    RegistrationManifest, RoleAuthority, RoleCardinality, StatePropertyDefinition, TargetKind,
    TypedSemanticId, ValueType,
};
use latticeaxiom_core::{
    CanonicalHash, CanonicalJsonError, CapabilityId, PackageName, SchemaId, StableId,
    canonical_json_hash,
};
pub use latticeaxiom_core::{NamespaceGrant, NamespaceGrantor, NamespaceGrantorRef};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;

/// Current schema of compiler-owned activation receipts.
pub const REGISTRATION_COMPILE_RECEIPT_SCHEMA_VERSION: u32 = 1;

/// A public schema contract absent from the legacy registration fragment.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SchemaDeclaration {
    /// Schema ID, including its positive contract major.
    pub id: SchemaId,
    /// Package owning the schema contract.
    pub declared_by: PackageName,
    /// Finite JSON value contract when semantic values use this schema.
    pub value_type: Option<ValueType>,
}

/// One stable callback exported by a package realization.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CallbackDeclaration {
    /// Versioned callback key.
    pub id: StableId,
    /// Package owning the callback.
    pub declared_by: PackageName,
    /// Canonical signature hash generated from the parameter model.
    pub signature_hash: CanonicalHash,
}

/// One scheduled system contract generated by the SDK.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SystemDeclaration {
    /// Exact system registration ID.
    pub id: StableId,
    /// Package owning the system.
    pub declared_by: PackageName,
    /// One accepted versioned semantic stage.
    pub stage: StableId,
    /// Callback implementing the system for the selected realization.
    pub callback: StableId,
    /// Hash of the single authoritative system signature.
    pub signature_hash: CanonicalHash,
    /// Systems in the same stage that must run before this system.
    #[serde(default)]
    pub after: BTreeSet<StableId>,
    /// Systems in the same stage that must run after this system.
    #[serde(default)]
    pub before: BTreeSet<StableId>,
}

/// Semantic contract families for which an owner may grant contributions.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum SemanticGrantKind {
    /// Additive Tag membership.
    Tag,
    /// Conflict-merged Map values.
    Map,
}

/// Explicit owner grant for a foreign package to contribute self-owned targets.
#[derive(Clone, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SemanticContributionGrant {
    /// Contract family covered by the grant.
    pub kind: SemanticGrantKind,
    /// Typed Tag or Map contract.
    pub contract: TypedSemanticId,
    /// Package allowed to contribute targets that it owns.
    pub grantee: PackageName,
}

/// Validated registration inputs for one exact locked package.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PackageRegistrationInput {
    /// Canonical package registration manifest.
    pub manifest: RegistrationManifest,
    /// Public schemas keyed by their canonical schema ID.
    #[serde(default)]
    pub schemas: BTreeMap<SchemaId, SchemaDeclaration>,
    /// Scheduled systems keyed by exact registration ID.
    #[serde(default)]
    pub systems: BTreeMap<StableId, SystemDeclaration>,
    /// Exported callbacks keyed by callback key.
    #[serde(default)]
    pub callbacks: BTreeMap<StableId, CallbackDeclaration>,
    /// Capability contracts implemented by this exact package realization.
    #[serde(default)]
    pub provided_capabilities: BTreeSet<CapabilityId>,
    /// Contribution grants issued by semantic contracts owned by this package.
    #[serde(default)]
    pub semantic_grants: BTreeSet<SemanticContributionGrant>,
}

/// Borrowed complete input to deterministic registration compilation.
#[derive(Clone, Copy, Debug)]
pub struct RegistrationCompileInput<'a> {
    /// Evaluated composition whose hashes are frozen by `graph`.
    pub composition: &'a CompositionSpec,
    /// Exact, verified package closure.
    pub graph: &'a LockedGameGraph,
    /// Exactly one registration contract for every package in `graph`.
    pub packages: &'a BTreeMap<PackageName, PackageRegistrationInput>,
}

/// Dense bitset for one compiled semantic Tag.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NumericTagTable {
    /// Registry kind indexed by the bitset.
    pub target_kind: TargetKind,
    /// Little-indexed words; bit `n` addresses numeric target `n`.
    pub words: Vec<u64>,
}

/// Numeric-keyed values for one typed semantic Map.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct NumericMapTable {
    /// Registry kind indexed by the table.
    pub target_kind: TargetKind,
    /// Schema used to validate every value.
    pub value_schema: SchemaId,
    /// Values keyed by process-local numeric target IDs.
    pub values: BTreeMap<NumericRegistrationId, Value>,
}

/// Compiler-owned semantic runtime tables missing from the legacy image DTO.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CompiledSemanticImage {
    /// Numeric Tag tables keyed by typed Tag contract.
    pub tags: BTreeMap<TypedSemanticId, NumericTagTable>,
    /// Numeric Map tables keyed by typed Map contract.
    pub maps: BTreeMap<TypedSemanticId, NumericMapTable>,
    /// State-property definitions keyed by stable contract ID.
    pub state_properties: BTreeMap<StableId, StatePropertyDefinition>,
    /// Accepted static-data affordance definitions.
    pub affordances: BTreeMap<StableId, AffordanceDefinition>,
    /// Role definitions keyed by stable Role ID.
    pub roles: BTreeMap<StableId, ContentRoleDefinition>,
    /// Numeric Role lookups keyed by stable Role ID.
    pub role_bindings: BTreeMap<StableId, Vec<NumericRegistrationId>>,
    /// Canonical hash of the complete compiled semantic runtime payload.
    pub semantic_hash: CanonicalHash,
}

impl CompiledSemanticImage {
    /// Recomputes the semantic image hash.
    ///
    /// # Errors
    ///
    /// Returns [`CanonicalJsonError`] if canonical JSON encoding fails.
    pub fn recompute_hash(&self) -> Result<CanonicalHash, CanonicalJsonError> {
        canonical_json_hash(&CompiledSemanticImageIdentity::from(self))
    }
}

#[derive(Serialize)]
struct CompiledSemanticImageIdentity<'a> {
    tags: &'a BTreeMap<TypedSemanticId, NumericTagTable>,
    maps: &'a BTreeMap<TypedSemanticId, NumericMapTable>,
    state_properties: &'a BTreeMap<StableId, StatePropertyDefinition>,
    affordances: &'a BTreeMap<StableId, AffordanceDefinition>,
    roles: &'a BTreeMap<StableId, ContentRoleDefinition>,
    role_bindings: &'a BTreeMap<StableId, Vec<NumericRegistrationId>>,
}

impl<'a> From<&'a CompiledSemanticImage> for CompiledSemanticImageIdentity<'a> {
    fn from(image: &'a CompiledSemanticImage) -> Self {
        Self {
            tags: &image.tags,
            maps: &image.maps,
            state_properties: &image.state_properties,
            affordances: &image.affordances,
            roles: &image.roles,
            role_bindings: &image.role_bindings,
        }
    }
}

/// Deterministic reason selecting one Role binding.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum RoleSelectionRule {
    /// A single normal candidate satisfied the contract.
    Unique,
    /// The frozen composition profile selected the target.
    Profile,
    /// A single fallback wave supplied the target.
    Fallback,
}

/// Canonical Role result retained for world freezing and explanation.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RoleBindingReceipt {
    /// Selected stable target IDs.
    pub targets: Vec<StableId>,
    /// Rule that selected the targets.
    pub selected_by: RoleSelectionRule,
}

/// Structured, stable semantic resolution evidence.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields, rename_all = "kebab-case", tag = "step")]
pub enum SemanticResolutionStep {
    /// Deterministic candidates considered for one Role.
    Candidates {
        /// Role being resolved.
        role: StableId,
        /// Sorted candidate targets.
        targets: Vec<StableId>,
    },
    /// One required Role had no candidate before the fallback wave.
    Missing {
        /// Role deferred to fallback selection.
        role: StableId,
    },
    /// One atomic fallback bundle became active.
    FallbackActivated {
        /// Activated bundle ID.
        bundle: StableId,
        /// Missing Roles authorizing activation.
        roles: Vec<StableId>,
    },
    /// Final binding selected for one Role.
    Bound {
        /// Role being resolved.
        role: StableId,
        /// Sorted selected targets.
        targets: Vec<StableId>,
        /// Selection rule.
        selected_by: RoleSelectionRule,
    },
}

/// Frozen semantic resolution, separately content-addressed from the image.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SemanticResolutionReceipt {
    /// Receipt schema version.
    pub schema_version: u32,
    /// Frozen graph semantic hash.
    pub graph_hash: CanonicalHash,
    /// Closure-wide semantic contract hash shared by every compiler receipt.
    pub registration_semantic_hash: CanonicalHash,
    /// Complete compiled semantic image hash.
    pub semantic_image_hash: CanonicalHash,
    /// Active unconditional and fallback bundle IDs.
    pub active_bundles: BTreeSet<StableId>,
    /// Frozen Role bindings.
    pub role_bindings: BTreeMap<StableId, RoleBindingReceipt>,
    /// Deterministically sorted resolution evidence.
    pub explanation: Vec<SemanticResolutionStep>,
    /// Content address of all preceding fields.
    pub receipt_hash: CanonicalHash,
}

impl SemanticResolutionReceipt {
    /// Recomputes this receipt's content address.
    ///
    /// # Errors
    ///
    /// Returns [`CanonicalJsonError`] if canonical JSON encoding fails.
    pub fn recompute_hash(&self) -> Result<CanonicalHash, CanonicalJsonError> {
        canonical_json_hash(&SemanticReceiptIdentity::from(self))
    }
}

#[derive(Serialize)]
struct SemanticReceiptIdentity<'a> {
    schema_version: u32,
    graph_hash: CanonicalHash,
    registration_semantic_hash: CanonicalHash,
    semantic_image_hash: CanonicalHash,
    active_bundles: &'a BTreeSet<StableId>,
    role_bindings: &'a BTreeMap<StableId, RoleBindingReceipt>,
    explanation: &'a [SemanticResolutionStep],
}

impl<'a> From<&'a SemanticResolutionReceipt> for SemanticReceiptIdentity<'a> {
    fn from(receipt: &'a SemanticResolutionReceipt) -> Self {
        Self {
            schema_version: receipt.schema_version,
            graph_hash: receipt.graph_hash,
            registration_semantic_hash: receipt.registration_semantic_hash,
            semantic_image_hash: receipt.semantic_image_hash,
            active_bundles: &receipt.active_bundles,
            role_bindings: &receipt.role_bindings,
            explanation: &receipt.explanation,
        }
    }
}

/// Numeric layout and schedule receipt used by the activation gate.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RegistrationImageReceipt {
    /// Receipt schema version.
    pub schema_version: u32,
    /// Frozen graph semantic hash.
    pub graph_hash: CanonicalHash,
    /// Closure-wide semantic contract hash, excluding provenance.
    pub registration_semantic_hash: CanonicalHash,
    /// Exact legacy registration image hash.
    pub image_hash: CanonicalHash,
    /// Per-kind dense numeric layouts.
    pub numeric_ids: BTreeMap<RegistrationKind, BTreeMap<StableId, NumericRegistrationId>>,
    /// Deterministic schedule after stage and edge compilation.
    pub schedule: Vec<StableId>,
    /// Content address of all preceding fields.
    pub receipt_hash: CanonicalHash,
}

impl RegistrationImageReceipt {
    /// Recomputes this receipt's content address.
    ///
    /// # Errors
    ///
    /// Returns [`CanonicalJsonError`] if canonical JSON encoding fails.
    pub fn recompute_hash(&self) -> Result<CanonicalHash, CanonicalJsonError> {
        canonical_json_hash(&ImageReceiptIdentity::from(self))
    }

    /// Verifies the receipt hash and dense per-kind numeric layout.
    ///
    /// # Errors
    ///
    /// Returns [`ReceiptValidationError`] for an unsupported schema, a hash
    /// mismatch, or a gap/reordering in any numeric table.
    pub fn verify(&self) -> Result<(), ReceiptValidationError> {
        verify_schema(self.schema_version)?;
        for (kind, table) in &self.numeric_ids {
            for (expected, (stable, actual)) in table.iter().enumerate() {
                if stable.kind() != registration_kind_name(*kind) {
                    return Err(ReceiptValidationError::NumericKindMismatch {
                        kind: *kind,
                        stable: stable.clone(),
                    });
                }
                let expected = u32::try_from(expected)
                    .map_err(|_| ReceiptValidationError::NumericTableTooLarge { kind: *kind })?;
                if actual.0 != expected {
                    return Err(ReceiptValidationError::NonDenseNumericIds {
                        kind: *kind,
                        stable: stable.clone(),
                        expected,
                        actual: actual.0,
                    });
                }
            }
        }
        verify_hash(self.receipt_hash, self.recompute_hash()?)
    }
}

#[derive(Serialize)]
struct ImageReceiptIdentity<'a> {
    schema_version: u32,
    graph_hash: CanonicalHash,
    registration_semantic_hash: CanonicalHash,
    image_hash: CanonicalHash,
    numeric_ids: &'a BTreeMap<RegistrationKind, BTreeMap<StableId, NumericRegistrationId>>,
    schedule: &'a [StableId],
}

impl<'a> From<&'a RegistrationImageReceipt> for ImageReceiptIdentity<'a> {
    fn from(receipt: &'a RegistrationImageReceipt) -> Self {
        Self {
            schema_version: receipt.schema_version,
            graph_hash: receipt.graph_hash,
            registration_semantic_hash: receipt.registration_semantic_hash,
            image_hash: receipt.image_hash,
            numeric_ids: &receipt.numeric_ids,
            schedule: &receipt.schedule,
        }
    }
}

/// One validated callback binding and every stable consumer using it.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CallbackBinding {
    /// Package owning the callback.
    pub owner: PackageName,
    /// Canonical callback signature hash.
    pub signature_hash: CanonicalHash,
    /// Systems or providers that consume this callback.
    pub consumers: BTreeSet<StableId>,
}

/// Independently retained callback contract for one scheduled system.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SystemCallbackProjection {
    /// Callback key selected by the system declaration.
    pub callback: StableId,
    /// Canonical system signature hash that must match the callback contract.
    pub signature_hash: CanonicalHash,
}

/// Callback map independently verified before any package code executes.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CallbackMapReceipt {
    /// Receipt schema version.
    pub schema_version: u32,
    /// Frozen graph semantic hash.
    pub graph_hash: CanonicalHash,
    /// Closure-wide semantic contract hash shared by every compiler receipt.
    pub registration_semantic_hash: CanonicalHash,
    /// Callback bindings keyed by stable callback key.
    pub callbacks: BTreeMap<StableId, CallbackBinding>,
    /// Scheduled systems independently projected to callback key and signature.
    pub systems: BTreeMap<StableId, SystemCallbackProjection>,
    /// Content address of all preceding fields.
    pub callback_map_hash: CanonicalHash,
}

impl CallbackMapReceipt {
    /// Recomputes the callback-map hash.
    ///
    /// # Errors
    ///
    /// Returns [`CanonicalJsonError`] if canonical JSON encoding fails.
    pub fn recompute_hash(&self) -> Result<CanonicalHash, CanonicalJsonError> {
        canonical_json_hash(&CallbackReceiptIdentity::from(self))
    }

    /// Verifies schema and callback-map hash.
    ///
    /// # Errors
    ///
    /// Returns [`ReceiptValidationError`] for an unsupported schema or mismatch.
    pub fn verify(&self) -> Result<(), ReceiptValidationError> {
        verify_schema(self.schema_version)?;
        for (system, projection) in &self.systems {
            let Some(callback) = self.callbacks.get(&projection.callback) else {
                return Err(ReceiptValidationError::SystemCallbackProjectionMismatch {
                    system: system.clone(),
                });
            };
            if system.kind() != "system"
                || callback.signature_hash != projection.signature_hash
                || !callback.consumers.contains(system)
            {
                return Err(ReceiptValidationError::SystemCallbackProjectionMismatch {
                    system: system.clone(),
                });
            }
        }
        for (callback, binding) in &self.callbacks {
            for consumer in binding
                .consumers
                .iter()
                .filter(|consumer| consumer.kind() == "system")
            {
                let Some(projection) = self.systems.get(consumer) else {
                    return Err(ReceiptValidationError::SystemCallbackProjectionMismatch {
                        system: consumer.clone(),
                    });
                };
                if &projection.callback != callback
                    || projection.signature_hash != binding.signature_hash
                {
                    return Err(ReceiptValidationError::SystemCallbackProjectionMismatch {
                        system: consumer.clone(),
                    });
                }
            }
        }
        verify_hash(self.callback_map_hash, self.recompute_hash()?)
    }
}

#[derive(Serialize)]
struct CallbackReceiptIdentity<'a> {
    schema_version: u32,
    graph_hash: CanonicalHash,
    registration_semantic_hash: CanonicalHash,
    callbacks: &'a BTreeMap<StableId, CallbackBinding>,
    systems: &'a BTreeMap<StableId, SystemCallbackProjection>,
}

impl<'a> From<&'a CallbackMapReceipt> for CallbackReceiptIdentity<'a> {
    fn from(receipt: &'a CallbackMapReceipt) -> Self {
        Self {
            schema_version: receipt.schema_version,
            graph_hash: receipt.graph_hash,
            registration_semantic_hash: receipt.registration_semantic_hash,
            callbacks: &receipt.callbacks,
            systems: &receipt.systems,
        }
    }
}

/// Provenance projection for one package registration contract.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PackageProvenanceReceipt {
    /// Semantic manifest hash verified against the lock.
    pub manifest_semantic_hash: CanonicalHash,
    /// Source/producer provenance projection hash.
    pub manifest_provenance_hash: CanonicalHash,
    /// Producer metadata retained outside semantic identity.
    pub producer: ManifestProducer,
}

/// Source and producer receipt separated from semantic and artifact identity.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RegistrationProvenanceReceipt {
    /// Receipt schema version.
    pub schema_version: u32,
    /// Exact lock hash, including source and artifact receipts.
    pub graph_lock_hash: CanonicalHash,
    /// Composition provenance hash frozen by the lock.
    pub composition_provenance_hash: CanonicalHash,
    /// Closure-wide semantic contract hash shared by every compiler receipt.
    pub registration_semantic_hash: CanonicalHash,
    /// Package receipts keyed by locked logical package name.
    pub packages: BTreeMap<PackageName, PackageProvenanceReceipt>,
    /// Content address of all preceding fields.
    pub provenance_hash: CanonicalHash,
}

impl RegistrationProvenanceReceipt {
    /// Recomputes the provenance receipt hash.
    ///
    /// # Errors
    ///
    /// Returns [`CanonicalJsonError`] if canonical JSON encoding fails.
    pub fn recompute_hash(&self) -> Result<CanonicalHash, CanonicalJsonError> {
        canonical_json_hash(&ProvenanceReceiptIdentity::from(self))
    }

    /// Verifies schema and provenance hash.
    ///
    /// # Errors
    ///
    /// Returns [`ReceiptValidationError`] for an unsupported schema or mismatch.
    pub fn verify(&self) -> Result<(), ReceiptValidationError> {
        verify_schema(self.schema_version)?;
        verify_hash(self.provenance_hash, self.recompute_hash()?)
    }
}

#[derive(Serialize)]
struct ProvenanceReceiptIdentity<'a> {
    schema_version: u32,
    graph_lock_hash: CanonicalHash,
    composition_provenance_hash: CanonicalHash,
    registration_semantic_hash: CanonicalHash,
    packages: &'a BTreeMap<PackageName, PackageProvenanceReceipt>,
}

impl<'a> From<&'a RegistrationProvenanceReceipt> for ProvenanceReceiptIdentity<'a> {
    fn from(receipt: &'a RegistrationProvenanceReceipt) -> Self {
        Self {
            schema_version: receipt.schema_version,
            graph_lock_hash: receipt.graph_lock_hash,
            composition_provenance_hash: receipt.composition_provenance_hash,
            registration_semantic_hash: receipt.registration_semantic_hash,
            packages: &receipt.packages,
        }
    }
}

/// Fully compiled, process-portable registration output.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CompiledRegistration {
    /// Legacy closure-wide image consumed by current host code.
    pub image: RegistrationImage,
    /// Numeric semantic tables and retained definitions.
    pub semantic_image: CompiledSemanticImage,
    /// Frozen Role and fallback resolution.
    pub semantic_receipt: SemanticResolutionReceipt,
    /// Numeric layout and schedule receipt.
    pub image_receipt: RegistrationImageReceipt,
    /// Callback binding receipt.
    pub callback_receipt: CallbackMapReceipt,
    /// Producer and source provenance receipt.
    pub provenance_receipt: RegistrationProvenanceReceipt,
}

impl CompiledRegistration {
    /// Verifies all self-contained hashes and cross-receipt bindings.
    ///
    /// # Errors
    ///
    /// Returns [`ReceiptValidationError`] if any receipt is malformed,
    /// mismatched, or bound to a different image or graph.
    pub fn verify(&self) -> Result<(), ReceiptValidationError> {
        self.image
            .verify_image_hash()
            .map_err(|error| ReceiptValidationError::Image(error.to_string()))?;
        self.image_receipt.verify()?;
        let mut flattened_numeric_ids = BTreeMap::new();
        for table in self.image_receipt.numeric_ids.values() {
            for (stable, numeric) in table {
                if flattened_numeric_ids
                    .insert(stable.clone(), *numeric)
                    .is_some()
                {
                    return Err(ReceiptValidationError::DuplicateNumericStableId {
                        stable: stable.clone(),
                    });
                }
            }
        }
        if flattened_numeric_ids != self.image.numeric_ids {
            return Err(ReceiptValidationError::CrossReceiptMismatch {
                field: "numeric-ids",
            });
        }
        self.callback_receipt.verify()?;
        self.provenance_receipt.verify()?;
        verify_schema(self.semantic_receipt.schema_version)?;
        verify_hash(
            self.semantic_receipt.receipt_hash,
            self.semantic_receipt.recompute_hash()?,
        )?;
        verify_hash(
            self.semantic_image.semantic_hash,
            self.semantic_image.recompute_hash()?,
        )?;
        if self.image.image_hash != self.image_receipt.image_hash {
            return Err(ReceiptValidationError::CrossReceiptMismatch {
                field: "image-hash",
            });
        }
        if self.semantic_image.semantic_hash != self.semantic_receipt.semantic_image_hash {
            return Err(ReceiptValidationError::CrossReceiptMismatch {
                field: "semantic-image-hash",
            });
        }
        let graph_hash = self.image.graph_hash;
        if self.image_receipt.graph_hash != graph_hash
            || self.callback_receipt.graph_hash != graph_hash
            || self.semantic_receipt.graph_hash != graph_hash
        {
            return Err(ReceiptValidationError::CrossReceiptMismatch {
                field: "graph-hash",
            });
        }
        let registration_semantic_hash = self.image_receipt.registration_semantic_hash;
        if self.semantic_receipt.registration_semantic_hash != registration_semantic_hash
            || self.callback_receipt.registration_semantic_hash != registration_semantic_hash
            || self.provenance_receipt.registration_semantic_hash != registration_semantic_hash
        {
            return Err(ReceiptValidationError::CrossReceiptMismatch {
                field: "registration-semantic-hash",
            });
        }
        if self.image.schedule != self.image_receipt.schedule {
            return Err(ReceiptValidationError::CrossReceiptMismatch { field: "schedule" });
        }
        verify_image_structure(self)?;
        verify_semantic_projection(self)?;
        verify_explanation_projection(self)?;
        verify_callback_projection(self)?;
        verify_visible_owners(self)?;
        Ok(())
    }

    /// Verifies the provenance package projection against one trusted locked graph.
    ///
    /// This check closes the external trust boundary that cannot be reconstructed
    /// from the self-contained compiler receipts alone.
    ///
    /// # Errors
    ///
    /// Returns [`ReceiptValidationError`] when the provenance receipt is invalid,
    /// its package set differs from the lock, or any package manifest hash differs.
    pub fn verify_locked_manifests(
        &self,
        graph: &LockedGameGraph,
    ) -> Result<(), ReceiptValidationError> {
        self.provenance_receipt.verify()?;
        if self
            .provenance_receipt
            .packages
            .keys()
            .ne(graph.packages.keys())
        {
            return Err(ReceiptValidationError::LockedPackageSetMismatch);
        }
        for (package, locked) in &graph.packages {
            let Some(provenance) = self.provenance_receipt.packages.get(package) else {
                return Err(ReceiptValidationError::LockedPackageSetMismatch);
            };
            if provenance.manifest_semantic_hash != locked.manifest_hash {
                return Err(ReceiptValidationError::LockedManifestSemanticHashMismatch {
                    package: package.clone(),
                    locked: locked.manifest_hash,
                    receipt: provenance.manifest_semantic_hash,
                });
            }
        }
        Ok(())
    }
}

fn mismatch(field: &'static str) -> ReceiptValidationError {
    ReceiptValidationError::CrossReceiptMismatch { field }
}

fn verify_image_structure(compiled: &CompiledRegistration) -> Result<(), ReceiptValidationError> {
    if compiled
        .image
        .owners
        .keys()
        .ne(compiled.image.numeric_ids.keys())
    {
        return Err(mismatch("owner-keys"));
    }

    let schema_table = compiled
        .image_receipt
        .numeric_ids
        .get(&RegistrationKind::Schema);
    let schema_numeric_keys = schema_table.into_iter().flat_map(BTreeMap::keys);
    if schema_numeric_keys.ne(compiled
        .image
        .schema_owners
        .keys()
        .map(SchemaId::as_stable_id))
    {
        return Err(mismatch("schema-owner-keys"));
    }
    for (schema, owner) in &compiled.image.schema_owners {
        if compiled.image.owners.get(schema.as_stable_id()) != Some(owner) {
            return Err(mismatch("schema-owner"));
        }
    }
    if !compiled
        .image
        .authoritative
        .iter()
        .all(|id| compiled.image.numeric_ids.contains_key(id))
    {
        return Err(mismatch("authoritative"));
    }

    let scheduled = compiled.image.schedule.iter().collect::<BTreeSet<_>>();
    if scheduled.len() != compiled.image.schedule.len() {
        return Err(mismatch("schedule-duplicates"));
    }
    let systems = compiled
        .image_receipt
        .numeric_ids
        .get(&RegistrationKind::System)
        .into_iter()
        .flat_map(BTreeMap::keys)
        .collect::<BTreeSet<_>>();
    if scheduled != systems {
        return Err(mismatch("schedule-system-set"));
    }
    Ok(())
}

// The three semantic projections intentionally stay in one auditable verifier.
#[allow(clippy::too_many_lines)]
fn verify_semantic_projection(
    compiled: &CompiledRegistration,
) -> Result<(), ReceiptValidationError> {
    if compiled.image.semantics.active_bundles != compiled.semantic_receipt.active_bundles {
        return Err(mismatch("semantic-active-bundles"));
    }
    let stable_bindings = compiled
        .semantic_receipt
        .role_bindings
        .iter()
        .map(|(role, binding)| (role.clone(), binding.targets.clone()))
        .collect::<BTreeMap<_, _>>();
    if compiled.image.semantics.role_bindings != stable_bindings {
        return Err(mismatch("semantic-role-bindings"));
    }
    if compiled
        .semantic_image
        .roles
        .keys()
        .ne(compiled.semantic_receipt.role_bindings.keys())
        || compiled
            .semantic_image
            .roles
            .keys()
            .ne(compiled.semantic_image.role_bindings.keys())
    {
        return Err(mismatch("semantic-role-keys"));
    }
    for (role_id, definition) in &compiled.semantic_image.roles {
        if role_id != &definition.id {
            return Err(mismatch("semantic-definition-key"));
        }
        let Some(kind) = registration_kind_for_semantic_target(definition.accepts.target_kind)
        else {
            return Err(mismatch("semantic-target-kind"));
        };
        let Some(binding) = compiled.semantic_receipt.role_bindings.get(role_id) else {
            return Err(mismatch("semantic-role-bindings"));
        };
        if binding.targets.windows(2).any(|pair| pair[0] >= pair[1]) {
            return Err(mismatch("semantic-role-bindings"));
        }
        let cardinality_valid = match definition.cardinality {
            RoleCardinality::ExactlyOne => binding.targets.len() == 1,
            RoleCardinality::ZeroOrOne => binding.targets.len() <= 1,
            RoleCardinality::OneOrMore => !binding.targets.is_empty(),
        };
        if !cardinality_valid
            || (binding.selected_by == RoleSelectionRule::Profile
                && definition.authority != RoleAuthority::Profile)
        {
            return Err(mismatch("semantic-role-bindings"));
        }
        let Some(table) = compiled.image_receipt.numeric_ids.get(&kind) else {
            return Err(mismatch("semantic-role-bindings"));
        };
        let numeric = binding
            .targets
            .iter()
            .map(|target| {
                table
                    .get(target)
                    .copied()
                    .ok_or_else(|| mismatch("semantic-role-bindings"))
            })
            .collect::<Result<Vec<_>, _>>()?;
        if compiled.semantic_image.role_bindings.get(role_id) != Some(&numeric) {
            return Err(mismatch("semantic-role-bindings"));
        }
    }

    if compiled
        .image
        .semantics
        .tags
        .keys()
        .ne(compiled.semantic_image.tags.keys())
    {
        return Err(mismatch("semantic-tags"));
    }
    for (tag, members) in &compiled.image.semantics.tags {
        let Some(kind) = registration_kind_for_semantic_target(tag.target_kind) else {
            return Err(mismatch("semantic-target-kind"));
        };
        let table = compiled.image_receipt.numeric_ids.get(&kind);
        let mut words = vec![0_u64; table.map_or(0, |rows| rows.len().div_ceil(64))];
        for member in members {
            let numeric = table
                .and_then(|rows| rows.get(member))
                .ok_or_else(|| mismatch("semantic-tags"))?;
            let index = usize::try_from(numeric.0).map_err(|_| mismatch("semantic-tags"))?;
            let word = words
                .get_mut(index / 64)
                .ok_or_else(|| mismatch("semantic-tags"))?;
            *word |= 1_u64 << (index % 64);
        }
        let Some(numeric) = compiled.semantic_image.tags.get(tag) else {
            return Err(mismatch("semantic-tags"));
        };
        if numeric.target_kind != tag.target_kind || numeric.words != words {
            return Err(mismatch("semantic-tags"));
        }
    }

    if compiled
        .image
        .semantics
        .maps
        .keys()
        .ne(compiled.semantic_image.maps.keys())
    {
        return Err(mismatch("semantic-maps"));
    }
    for (map, stable_values) in &compiled.image.semantics.maps {
        let Some(kind) = registration_kind_for_semantic_target(map.target_kind) else {
            return Err(mismatch("semantic-target-kind"));
        };
        let table = compiled.image_receipt.numeric_ids.get(&kind);
        let numeric_values = stable_values
            .iter()
            .map(|(target, value)| {
                let numeric = table
                    .and_then(|rows| rows.get(target))
                    .copied()
                    .ok_or_else(|| mismatch("semantic-maps"))?;
                Ok((numeric, value.clone()))
            })
            .collect::<Result<BTreeMap<_, _>, ReceiptValidationError>>()?;
        let Some(numeric) = compiled.semantic_image.maps.get(map) else {
            return Err(mismatch("semantic-maps"));
        };
        if numeric.target_kind != map.target_kind
            || numeric.values != numeric_values
            || !compiled
                .image
                .schema_owners
                .contains_key(&numeric.value_schema)
        {
            return Err(mismatch("semantic-maps"));
        }
    }

    for (id, definition) in &compiled.semantic_image.state_properties {
        if id != &definition.id
            || definition.target_kind != TargetKind::Block
            || !compiled
                .image
                .schema_owners
                .contains_key(&definition.value_schema)
        {
            return Err(mismatch("semantic-definition"));
        }
    }
    for (id, definition) in &compiled.semantic_image.affordances {
        if id != &definition.id
            || registration_kind_for_semantic_target(definition.target_kind).is_none()
            || !compiled
                .image
                .schema_owners
                .contains_key(&definition.request_schema)
            || !compiled
                .image
                .schema_owners
                .contains_key(&definition.response_schema)
            || definition.policy != AffordancePolicy::StaticData
            || definition.callback.is_some()
        {
            return Err(mismatch("semantic-definition"));
        }
    }
    Ok(())
}

fn verify_explanation_projection(
    compiled: &CompiledRegistration,
) -> Result<(), ReceiptValidationError> {
    let mut missing = BTreeSet::new();
    let mut activated = BTreeSet::new();
    let mut last_bound = BTreeMap::new();
    for step in &compiled.semantic_receipt.explanation {
        match step {
            SemanticResolutionStep::Candidates { role, targets } => {
                if !valid_role_targets(compiled, role, targets) {
                    return Err(mismatch("semantic-explanation"));
                }
            }
            SemanticResolutionStep::Missing { role } => {
                if !compiled.semantic_image.roles.contains_key(role)
                    || !missing.insert(role.clone())
                {
                    return Err(mismatch("semantic-explanation"));
                }
            }
            SemanticResolutionStep::FallbackActivated { bundle, roles } => {
                if !compiled.semantic_receipt.active_bundles.contains(bundle)
                    || !activated.insert(bundle.clone())
                    || roles.is_empty()
                    || !roles.windows(2).all(|pair| pair[0] < pair[1])
                    || !roles
                        .iter()
                        .all(|role| compiled.semantic_image.roles.contains_key(role))
                {
                    return Err(mismatch("semantic-explanation"));
                }
            }
            SemanticResolutionStep::Bound {
                role,
                targets,
                selected_by,
            } => {
                if !valid_role_targets(compiled, role, targets) {
                    return Err(mismatch("semantic-explanation"));
                }
                last_bound.insert(
                    role.clone(),
                    RoleBindingReceipt {
                        targets: targets.clone(),
                        selected_by: *selected_by,
                    },
                );
            }
        }
    }
    if last_bound != compiled.semantic_receipt.role_bindings {
        return Err(mismatch("semantic-explanation"));
    }
    Ok(())
}

fn valid_role_targets(
    compiled: &CompiledRegistration,
    role: &StableId,
    targets: &[StableId],
) -> bool {
    let Some(definition) = compiled.semantic_image.roles.get(role) else {
        return false;
    };
    let Some(kind) = registration_kind_for_semantic_target(definition.accepts.target_kind) else {
        return false;
    };
    targets.windows(2).all(|pair| pair[0] < pair[1])
        && (targets.is_empty()
            || compiled
                .image_receipt
                .numeric_ids
                .get(&kind)
                .is_some_and(|table| targets.iter().all(|target| table.contains_key(target))))
}

fn verify_callback_projection(
    compiled: &CompiledRegistration,
) -> Result<(), ReceiptValidationError> {
    let systems = compiled.image.schedule.iter().collect::<BTreeSet<_>>();
    let projected_systems = compiled
        .callback_receipt
        .systems
        .keys()
        .collect::<BTreeSet<_>>();
    if systems != projected_systems {
        return Err(mismatch("callback-system-set"));
    }
    let mut expected = compiled
        .image
        .schedule
        .iter()
        .cloned()
        .collect::<BTreeSet<_>>();
    expected.extend(compiled.image.observability.info_items.keys().cloned());
    expected.extend(compiled.image.observability.inspect.keys().cloned());
    let mut seen = BTreeSet::new();
    for (callback, binding) in &compiled.callback_receipt.callbacks {
        if callback.kind() != "callback"
            || callback.major().is_none()
            || binding.consumers.is_empty()
            || !compiled
                .provenance_receipt
                .packages
                .contains_key(&binding.owner)
        {
            return Err(mismatch("callback-binding"));
        }
        for consumer in &binding.consumers {
            if !seen.insert(consumer.clone()) {
                return Err(mismatch("callback-consumers"));
            }
            if systems.contains(consumer) {
                if compiled.image.owners.get(consumer) != Some(&binding.owner) {
                    return Err(mismatch("callback-owner"));
                }
            } else if let Some(info) = compiled.image.observability.info_items.get(consumer) {
                if &info.callback != callback || info.declared_by != binding.owner {
                    return Err(mismatch("callback-consumers"));
                }
            } else if let Some(inspect) = compiled.image.observability.inspect.get(consumer) {
                if &inspect.callback != callback || inspect.declared_by != binding.owner {
                    return Err(mismatch("callback-consumers"));
                }
            } else {
                return Err(mismatch("callback-consumers"));
            }
        }
    }
    if seen != expected {
        return Err(mismatch("callback-consumers"));
    }
    Ok(())
}

fn verify_visible_owners(compiled: &CompiledRegistration) -> Result<(), ReceiptValidationError> {
    let packages = &compiled.provenance_receipt.packages;
    let image_owners_valid = compiled
        .image
        .owners
        .values()
        .all(|owner| packages.contains_key(owner))
        && compiled
            .image
            .schema_owners
            .values()
            .all(|owner| packages.contains_key(owner));
    let settings_owners_valid = compiled
        .image
        .settings
        .runtime
        .values()
        .all(|row| packages.contains_key(&row.declared_by))
        && compiled
            .image
            .settings
            .composition
            .values()
            .all(|row| packages.contains_key(&row.declared_by));
    let observability_owners_valid = compiled
        .image
        .observability
        .info_items
        .values()
        .all(|row| packages.contains_key(&row.declared_by))
        && compiled
            .image
            .observability
            .metrics
            .values()
            .all(|row| packages.contains_key(&row.declared_by))
        && compiled
            .image
            .observability
            .inspect
            .values()
            .all(|row| packages.contains_key(&row.declared_by))
        && compiled
            .image
            .observability
            .visualizers
            .values()
            .all(|row| packages.contains_key(&row.declared_by));
    if image_owners_valid && settings_owners_valid && observability_owners_valid {
        Ok(())
    } else {
        Err(mismatch("provenance-packages"))
    }
}

const fn registration_kind_for_semantic_target(target: TargetKind) -> Option<RegistrationKind> {
    match target {
        TargetKind::Dimension => Some(RegistrationKind::Dimension),
        TargetKind::Block => Some(RegistrationKind::Block),
        TargetKind::Item => Some(RegistrationKind::Item),
        TargetKind::Fluid => Some(RegistrationKind::Fluid),
        TargetKind::Biome => Some(RegistrationKind::Biome),
        TargetKind::Entity => None,
    }
}

/// Failure while verifying a persisted or transported compiler receipt.
#[derive(Debug, Error)]
pub enum ReceiptValidationError {
    /// Canonical JSON encoding failed.
    #[error(transparent)]
    Canonical(#[from] CanonicalJsonError),
    /// The receipt schema is unsupported.
    #[error("unsupported registration receipt schema {found}")]
    UnsupportedSchema {
        /// Encountered schema version.
        found: u32,
    },
    /// A claimed receipt hash differs from the normalized payload.
    #[error("receipt hash mismatch: expected {expected}, recomputed {actual}")]
    HashMismatch {
        /// Claimed content address.
        expected: CanonicalHash,
        /// Recomputed content address.
        actual: CanonicalHash,
    },
    /// A numeric registry table exceeds `u32` representability.
    #[error("numeric table for {kind:?} exceeds u32 representability")]
    NumericTableTooLarge {
        /// Affected registry kind.
        kind: RegistrationKind,
    },
    /// A numeric registry table contains a gap or noncanonical ordering.
    #[error("numeric table for {kind:?} assigns {stable}={actual}, expected dense ID {expected}")]
    NonDenseNumericIds {
        /// Affected registry kind.
        kind: RegistrationKind,
        /// Stable ID at the invalid position.
        stable: StableId,
        /// Required dense numeric ID.
        expected: u32,
        /// Actual numeric ID.
        actual: u32,
    },
    /// A stable ID was placed in a numeric table for another registry kind.
    #[error("numeric table for {kind:?} contains stable ID {stable} of another kind")]
    NumericKindMismatch {
        /// Numeric table containing the row.
        kind: RegistrationKind,
        /// Stable ID whose grammar kind disagrees.
        stable: StableId,
    },
    /// One stable ID appears in more than one per-kind numeric table.
    #[error("stable ID {stable} appears in multiple numeric tables")]
    DuplicateNumericStableId {
        /// Duplicated stable registration ID.
        stable: StableId,
    },
    /// The provenance package set differs from the trusted locked closure.
    #[error("registration provenance package set differs from the locked graph")]
    LockedPackageSetMismatch,
    /// One provenance manifest hash differs from its trusted locked package.
    #[error(
        "locked package {package} manifest hash {locked} differs from registration provenance {receipt}"
    )]
    LockedManifestSemanticHashMismatch {
        /// Package whose manifest projection differs.
        package: PackageName,
        /// Trusted manifest semantic hash from the lock.
        locked: CanonicalHash,
        /// Manifest semantic hash retained by the provenance receipt.
        receipt: CanonicalHash,
    },
    /// A scheduled system disagrees with its independent callback projection.
    #[error("scheduled system {system} disagrees with its callback projection")]
    SystemCallbackProjectionMismatch {
        /// Scheduled system with a missing or inconsistent projection.
        system: StableId,
    },
    /// The legacy image hash failed its own check.
    #[error("registration image failed verification: {0}")]
    Image(String),
    /// Separately hashed outputs do not bind the same payload.
    #[error("registration receipts disagree on {field}")]
    CrossReceiptMismatch {
        /// Cross-receipt field that disagreed.
        field: &'static str,
    },
}

const fn registration_kind_name(kind: RegistrationKind) -> &'static str {
    match kind {
        RegistrationKind::Dimension => "dimension",
        RegistrationKind::Block => "block",
        RegistrationKind::Item => "item",
        RegistrationKind::Fluid => "fluid",
        RegistrationKind::Biome => "biome",
        RegistrationKind::Component => "component",
        RegistrationKind::Message => "message",
        RegistrationKind::System => "system",
        RegistrationKind::Asset => "asset",
        RegistrationKind::Capability => "capability",
        RegistrationKind::Schema => "schema",
        RegistrationKind::Render => "render",
    }
}
fn verify_schema(schema_version: u32) -> Result<(), ReceiptValidationError> {
    if schema_version == REGISTRATION_COMPILE_RECEIPT_SCHEMA_VERSION {
        Ok(())
    } else {
        Err(ReceiptValidationError::UnsupportedSchema {
            found: schema_version,
        })
    }
}

fn verify_hash(
    expected: CanonicalHash,
    actual: CanonicalHash,
) -> Result<(), ReceiptValidationError> {
    if expected == actual {
        Ok(())
    } else {
        Err(ReceiptValidationError::HashMismatch { expected, actual })
    }
}
