//! Page-level settings errors. Persistence failures stay on the host.

use latticeaxiom_core::StableId;
use latticeaxiom_runtime_contracts::{SettingsCatalogError, SettingsOverlayError};
use thiserror::Error;

use crate::surface::SettingsSurfaceError;

/// Failure to open, navigate, or apply the official settings page.
#[derive(Clone, Debug, Eq, Error, PartialEq)]
pub enum SettingsPageError {
    /// Baseline catalog compilation failed.
    #[error(transparent)]
    Catalog(SettingsCatalogError),
    /// Effective values could not be resolved.
    #[error("settings page overlay failed: {0}")]
    Overlay(String),
    /// Presentation draft rejected the command.
    #[error(transparent)]
    Surface(#[from] SettingsSurfaceError),
    /// A semantic key generated by the page was invalid.
    #[error("settings page generated an invalid semantic key")]
    InvalidSemanticKey,
    /// Projection attempted to spawn a second UI root.
    #[error("settings page cannot create a second UI root")]
    SecondUiRoot,
    /// Navigation targeted an unknown category or section.
    #[error("settings page has no {target}")]
    UnknownTarget {
        /// Missing navigation target.
        target: String,
    },
    /// A reset targeted a setting absent from the page.
    #[error("settings page cannot reset {setting}")]
    UnknownSetting {
        /// Missing setting.
        setting: StableId,
    },
    /// The mock or real host rejected an apply.
    #[error("settings page host rejected apply: {reason}")]
    Host {
        /// Host diagnostic.
        reason: String,
    },
}

impl From<SettingsOverlayError> for SettingsPageError {
    fn from(value: SettingsOverlayError) -> Self {
        Self::Overlay(value.to_string())
    }
}
